--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KyanPHP/EnderPearlCooldown
build-by-default: true
branches:
- main
projects:
  EnderPearlCooldown:
    path: EnderPearlCooldown/
...
